### ISSUE TITLE
FileNotFoundError when try to reproduce results of pretrained model

### ISSUE THREAD

**Issue by Saibo-creator** [fartashf/vsepp#39]
Hey, 
     I had this issue when follow your readme to evaluate the pretrained model. I've set up the env variable, and` echo $RUN_PATH/` in terminal show the right path. 

```
>>> evaluation.evalrank("$RUN_PATH/coco_vse++/model_best.pth.tar", data_path="$DATA_PATH", split="test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/localdata/geng/lib/vsepp/evaluation.py", line 137, in evalrank
    checkpoint = torch.load(model_path, map_location=torch.device(device))
  File "/mnt/localdata/geng/anaconda3/envs/vsepp/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/mnt/localdata/geng/anaconda3/envs/vsepp/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/mnt/localdata/geng/anaconda3/envs/vsepp/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '$RUN_PATH/coco_vse++/model_best.pth.tar'
```

**Comment by fartashf** [comment]
Hi,
I'm afraid the example in the README is not exactly right.
You might want to either substitute RUN_PATH and DATA_PATH manually or define them as variables inside python and use the following command:
```
evaluation.evalrank("{RUN_PATH}/coco_vse++/model_best.pth.tar".format(RUN_PATH= RUN_PATH), data_path="{DATA_PATH}".format(DATA_PATH= DATA_PATH), split="test")
```
or run the command by passing the python lines as arguments to python:
```
python -c "\
from vocab import Vocabulary
import evaluation
evaluation.evalrank('$RUN_PATH/coco_vse++/model_best.pth.tar', data_path='$DATA_PATH', split='test')"
```
